- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories (Ubuntu)
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

  tasks:
    - include: tasks/cli_packages.yml
